"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ai = exports.AiService = exports.aiPath = void 0;
const errors_1 = require("@feathersjs/errors");
const authenticate_if_external_1 = require("../../hooks/authenticate-if-external");
exports.aiPath = 'ai';
/**
 * Minimal AI “edge-function replacement” service.
 * Actions:
 * - create({ action: 'generate-contract', contractId })
 * - create({ action: 'generate-legal-document', title, documentType, jurisdiction?, prompt? })
 *
 * If `LOVABLE_API_KEY` is configured, you can later replace the placeholder generation
 * with real gateway calls.
 */
class AiService {
    async create(data, params) {
        const user = params.user;
        if (!user?._id)
            throw new errors_1.errors.NotAuthenticated();
        if (data?.action === 'generate-contract') {
            const contractId = data.contractId;
            if (!contractId)
                throw new errors_1.errors.BadRequest('contractId is required');
            const contract = await params.app.service('rental-contracts').get(contractId, { provider: undefined });
            const content = [
                `RENTAL AGREEMENT (AUTO-GENERATED)`,
                ``,
                `Landlord ID: ${contract.landlordId}`,
                `Tenant ID: ${contract.tenantId}`,
                `Unit ID: ${contract.unitId}`,
                `Term: ${contract.startDate} to ${contract.endDate}`,
                `Monthly Rent: ${contract.monthlyRent} ${contract.rentCurrency || 'GHS'}`,
                ``,
                `This document is a placeholder contract generated by RentFlow API. Replace with real AI generation.`,
                `Jurisdiction: Ghana (default)`
            ].join('\n');
            await params.app.service('rental-contracts').patch(contractId, { content, status: 'sent' }, { provider: undefined });
            return { contractId, status: 'generated', content };
        }
        if (data?.action === 'generate-legal-document') {
            const title = data.title;
            const documentType = data.documentType;
            if (!title || !documentType)
                throw new errors_1.errors.BadRequest('title and documentType are required');
            const jurisdiction = data.jurisdiction || 'Ghana';
            const prompt = data.prompt || '';
            const content = [
                `${documentType.toUpperCase()} (AUTO-GENERATED)`,
                ``,
                `Title: ${title}`,
                `Jurisdiction: ${jurisdiction}`,
                ``,
                prompt ? `Notes:\n${prompt}\n` : '',
                `This legal document is a placeholder generated by RentFlow API. Replace with real AI generation.`
            ]
                .filter(Boolean)
                .join('\n');
            const doc = await params.app.service('legal-documents').create({ title, documentType, jurisdiction, content, metadata: { prompt } }, { user, provider: undefined });
            return doc;
        }
        throw new errors_1.errors.BadRequest('Unknown AI action');
    }
}
exports.AiService = AiService;
const ai = (app) => {
    // app is needed in create() via params; Feathers gives params.app only in hook context,
    // so we attach it through a before hook.
    app.use(exports.aiPath, new AiService(), { methods: ['create'], events: [] });
    app.service(exports.aiPath).hooks({
        before: {
            create: [
                (0, authenticate_if_external_1.authenticateIfExternal)('jwt'),
                async (context) => {
                    ;
                    context.params.app = context.app;
                    return context;
                }
            ]
        }
    });
};
exports.ai = ai;
//# sourceMappingURL=ai.js.map