"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.services = void 0;
const users_1 = require("./users/users");
const auth_management_1 = require("./auth-management/auth-management");
const mailer_1 = require("./mailer/mailer");
const user_roles_1 = require("./user-roles/user-roles");
const role_requests_1 = require("./role-requests/role-requests");
const refresh_tokens_1 = require("./refresh-tokens/refresh-tokens");
const properties_1 = require("./properties/properties");
const units_1 = require("./units/units");
const rental_applications_1 = require("./rental-applications/rental-applications");
const rental_contracts_1 = require("./rental-contracts/rental-contracts");
const maintenance_requests_1 = require("./maintenance-requests/maintenance-requests");
const communications_1 = require("./communications/communications");
const notices_1 = require("./notices/notices");
const exchange_rates_1 = require("./exchange-rates/exchange-rates");
const payments_1 = require("./payments/payments");
const legal_documents_1 = require("./legal-documents/legal-documents");
const virtual_viewing_requests_1 = require("./virtual-viewing-requests/virtual-viewing-requests");
const verification_documents_1 = require("./verification-documents/verification-documents");
const sms_1 = require("./sms/sms");
const ai_1 = require("./ai/ai");
const delete_account_1 = require("./delete-account/delete-account");
const paystack_webhook_1 = require("./paystack-webhook/paystack-webhook");
const files_1 = require("./files/files");
const files_uploader_1 = require("./files-uploader/files-uploader");
const agent_profiles_1 = require("./agent-profiles/agent-profiles");
const agent_assignments_1 = require("./agent-assignments/agent-assignments");
const agent_listing_requests_1 = require("./agent-listing-requests/agent-listing-requests");
const agent_ratings_1 = require("./agent-ratings/agent-ratings");
const property_manager_assignments_1 = require("./property-manager-assignments/property-manager-assignments");
const property_manager_listing_requests_1 = require("./property-manager-listing-requests/property-manager-listing-requests");
const property_manager_profiles_1 = require("./property-manager-profiles/property-manager-profiles");
const pm_ratings_1 = require("./pm-ratings/pm-ratings");
const agent_payouts_1 = require("./agent-payouts/agent-payouts");
const pm_payouts_1 = require("./pm-payouts/pm-payouts");
const threads_1 = require("./threads/threads");
const inquiries_1 = require("./inquiries/inquiries");
const chat_messages_1 = require("./chat-messages/chat-messages");
const favorites_1 = require("./favorites/favorites");
const dashboard_1 = require("./dashboard/dashboard");
const listing_sidebar_1 = require("./listing-sidebar/listing-sidebar");
const user_notifications_1 = require("./user-notifications/user-notifications");
const admin_bootstrap_1 = require("./admin-bootstrap/admin-bootstrap");
const admin_migrations_1 = require("./admin-migrations/admin-migrations");
const site_pages_1 = require("./site-pages/site-pages");
const user_notification_triggers_1 = require("../user-notification-triggers");
const services = (app) => {
    app.configure(mailer_1.mailer);
    app.configure(users_1.users);
    app.configure(auth_management_1.authManagement);
    app.configure(user_roles_1.userRoles);
    app.configure(role_requests_1.roleRequests);
    app.configure(refresh_tokens_1.refreshTokens);
    app.configure(properties_1.properties);
    app.configure(units_1.units);
    app.configure(rental_applications_1.rentalApplications);
    app.configure(rental_contracts_1.rentalContracts);
    app.configure(maintenance_requests_1.maintenanceRequests);
    app.configure(communications_1.communications);
    app.configure(notices_1.notices);
    app.configure(exchange_rates_1.exchangeRates);
    app.configure(payments_1.payments);
    app.configure(legal_documents_1.legalDocuments);
    app.configure(virtual_viewing_requests_1.virtualViewingRequests);
    app.configure(verification_documents_1.verificationDocuments);
    app.configure(sms_1.sms);
    app.configure(ai_1.ai);
    app.configure(delete_account_1.deleteAccount);
    app.configure(paystack_webhook_1.paystackWebhook);
    app.configure(files_1.files);
    app.configure(files_uploader_1.filesUploader);
    app.configure(agent_profiles_1.agentProfiles);
    app.configure(agent_assignments_1.agentAssignments);
    app.configure(agent_listing_requests_1.agentListingRequests);
    app.configure(agent_ratings_1.agentRatings);
    app.configure(property_manager_profiles_1.propertyManagerProfiles);
    app.configure(pm_ratings_1.pmRatings);
    app.configure(property_manager_assignments_1.propertyManagerAssignments);
    app.configure(property_manager_listing_requests_1.propertyManagerListingRequests);
    app.configure(agent_payouts_1.agentPayouts);
    app.configure(pm_payouts_1.pmPayouts);
    app.configure(threads_1.threads);
    app.configure(inquiries_1.inquiries);
    app.configure(chat_messages_1.chatMessages);
    app.configure(favorites_1.favorites);
    app.configure(user_notifications_1.userNotifications);
    app.configure(dashboard_1.dashboard);
    app.configure(listing_sidebar_1.listingSidebar);
    app.configure(admin_bootstrap_1.adminBootstrap);
    app.configure(admin_migrations_1.adminMigrations);
    app.configure(site_pages_1.sitePages);
    (0, user_notification_triggers_1.registerUserNotificationTriggers)(app);
};
exports.services = services;
//# sourceMappingURL=index.js.map