import type { Application, HookContext } from '../../declarations'
import { errors } from '@feathersjs/errors'
import { authenticateIfExternal } from '../../hooks/authenticate-if-external'

export const aiPath = 'ai'

/**
 * Minimal AI “edge-function replacement” service.
 * Actions:
 * - create({ action: 'generate-contract', contractId })
 * - create({ action: 'generate-legal-document', title, documentType, jurisdiction?, prompt? })
 *
 * If `LOVABLE_API_KEY` is configured, you can later replace the placeholder generation
 * with real gateway calls.
 */
export class AiService {
  async create(data: any, params: any) {
    const user = params.user
    if (!user?._id) throw new errors.NotAuthenticated()

    if (data?.action === 'generate-contract') {
      const contractId = data.contractId
      if (!contractId) throw new errors.BadRequest('contractId is required')

      const contract = await params.app.service('rental-contracts').get(contractId, { provider: undefined } as any)

      const content = [
        `RENTAL AGREEMENT (AUTO-GENERATED)`,
        ``,
        `Landlord ID: ${contract.landlordId}`,
        `Tenant ID: ${contract.tenantId}`,
        `Unit ID: ${contract.unitId}`,
        `Term: ${contract.startDate} to ${contract.endDate}`,
        `Monthly Rent: ${contract.monthlyRent} ${contract.rentCurrency || 'GHS'}`,
        ``,
        `This document is a placeholder contract generated by RentFlow API. Replace with real AI generation.`,
        `Jurisdiction: Ghana (default)`
      ].join('\n')

      await params.app.service('rental-contracts').patch(
        contractId,
        { content, status: 'sent' },
        { provider: undefined } as any
      )

      return { contractId, status: 'generated', content }
    }

    if (data?.action === 'generate-legal-document') {
      const title = data.title
      const documentType = data.documentType
      if (!title || !documentType) throw new errors.BadRequest('title and documentType are required')

      const jurisdiction = data.jurisdiction || 'Ghana'
      const prompt = data.prompt || ''

      const content = [
        `${documentType.toUpperCase()} (AUTO-GENERATED)`,
        ``,
        `Title: ${title}`,
        `Jurisdiction: ${jurisdiction}`,
        ``,
        prompt ? `Notes:\n${prompt}\n` : '',
        `This legal document is a placeholder generated by RentFlow API. Replace with real AI generation.`
      ]
        .filter(Boolean)
        .join('\n')

      const doc = await params.app.service('legal-documents').create(
        { title, documentType, jurisdiction, content, metadata: { prompt } },
        { user, provider: undefined } as any
      )

      return doc
    }

    throw new errors.BadRequest('Unknown AI action')
  }
}

export const ai = (app: Application) => {
  // app is needed in create() via params; Feathers gives params.app only in hook context,
  // so we attach it through a before hook.
  app.use(aiPath, new AiService() as any, { methods: ['create'], events: [] })

  app.service(aiPath).hooks({
    before: {
      create: [
        authenticateIfExternal('jwt'),
        async (context: HookContext) => {
          ;(context.params as any).app = context.app
          return context
        }
      ]
    }
  })
}

declare module '../../declarations' {
  interface ServiceTypes {
    [aiPath]: AiService
  }
}

